/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'remington' at '1/13/16 11:07 AM' with Gradle 2.4
 *
 * @author remington, @date 1/13/16 11:07 AM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
